# Generated by Django 2.2.3 on 2019-07-31 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photogur', '0003_auto_20190731_0317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='message',
            field=models.TextField(),
        ),
    ]
