# Generated by Django 2.2.3 on 2019-07-31 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photogur', '0004_auto_20190731_0324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='message',
            field=models.TextField(blank=True),
        ),
    ]
