# Generated by Django 2.2.3 on 2019-07-31 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photogur', '0006_auto_20190731_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='created_at',
        ),
    ]
